spring:
  application:
    name: spring-cloud-gateway-app

  cloud:
    gateway:
      routes:
#        - id: helloservice-route
#          uri: http://localhost:8071
#          predicates:
#            - Path=/rest/service1/**
#        - id: factorialservice-route
#          uri: http://localhost:8072
#          predicates:
#            - Path=/rest/service2/**

server:
  port: 8073
